esphome:
  name: ac-study-room
  friendly_name: ac-study-room

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Generated_By_ESPHome_Automatically"

ota:
  - platform: esphome
    password: "Generated_By_ESPHome_Automatically"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ac-Study-Room Fallback Hotspot"
    password: "Generated_By_ESPHome_Automatically"

captive_portal:

external_components:
  - source: components
    components: [hitachi_ac]

sensor:
  - platform: homeassistant
    name: temperature_study_room
    entity_id: sensor.study_room_temperature
    id: temp
    internal: true

  - platform: wifi_signal
    name: wifi rssi
    update_interval: 3600s

remote_transmitter:
  id: ir_tx
  pin: GPIO4
  carrier_duty_percent: 50%

remote_receiver:
  id: ir_rx
  pin:
    number: GPIO14
    inverted: true
    mode:
      input: true
      pullup: true
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%
  # dump: pronto

climate:
  - platform: hitachi_ac
    id: ac_study_room
    name: "ac_study_room"
    transmitter_id: ir_tx
    receiver_id: ir_rx
    visual:
      min_temperature: 18
      max_temperature: 40
      temperature_step: 0.1
    sensor: temp
    horizontal_default: "right"
    